name: Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '25 5 * * 1'
  push:
    branches: [main]

permissions:
  contents: read
  actions: read

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Run analysis
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7 (tag object: faaa5d804fc648d0fdb28822a8e36cf7d0a6132c)
        with:
          sarif_file: results.sarif
